
---
version: '1'

# App (Project) name
name: FX-Control-Plane

# App description
description: FX Testing.

# license
licenses:
  - APACHE LICENSE, VERSION 2.

imports:
  '@USName': FXLabs/Common/US-Names

# App environments
environments:
  - name: Stg
    baseUrl: http://stg1.fxlabs.io/api/v1
    # app access credentials
    auths:
      - name: Default
        authType: BASIC
        username: admin@fxlabs.io
        password: '{{@Vault.FXLabs/Stg-Admin-Pass}}'
  - name: Dev
    baseUrl: http://localhost:8080/api/v1
    # app access credentials
    auths:
      - name: Default
        authType: BASIC
        username: admin@fxlabs.io
        password: '{{@Vault.FXLabs/DevMachinePassword}}'

# Job profiles
jobs:
  - name: Stg
    environment: Stg
    tags:
      - V2
    regions: FXLabs/US_WEST_1
    cron: '0 0 12 * * ?'
    issueTracker: FXLabs/FX_Test_Automation
    notifications:
      - FXLabs/engineering
  - name: SANDBOX
    environment: Dev
    tags:
      - V2
    regions: FXLabs/Localhost
  - name: Dev
    environment: Dev
    tags:
      - V3
